name: "Release DeBank artifacts"

on:
  release:
    types:
      - created
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  REGISTRY: public.ecr.aws/b2h7a5c4/chaintable
  IMAGE: tempo-writer
  DOCKERFILE: Dockerfile.debank

jobs:
  build-artifacts:
    strategy:
      matrix:
        arch: [ amd64, arm64 ]
    runs-on: [self-hosted, "${{ matrix.arch }}"]
    permissions:
      contents: read
      id-token: write
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set env
        run: |
          echo "REVISION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          file: ${{ env.DOCKERFILE }}
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE }}:${{ matrix.arch }}-${{ env.REVISION }}
          provenance: false

  merge-docker-manifest:
    runs-on: [ self-hosted, general ]
    needs: build-artifacts
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set env
        run: |
          echo "REVISION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public

      - name: Merge manifest
        run: |
          docker pull --platform=linux/amd64 ${REGISTRY}/${IMAGE}:amd64-${REVISION}
          docker pull --platform=linux/arm64 ${REGISTRY}/${IMAGE}:arm64-${REVISION}
          docker buildx imagetools create --tag ${REGISTRY}/${IMAGE}:${REVISION} --tag ${REGISTRY}/${IMAGE}:latest ${REGISTRY}/${IMAGE}:amd64-${REVISION} ${REGISTRY}/${IMAGE}:arm64-${REVISION}
          docker rmi ${REGISTRY}/${IMAGE}:amd64-${REVISION}
          docker rmi ${REGISTRY}/${IMAGE}:arm64-${REVISION}

      - name: Lark Notification
        continue-on-error: true
        run: |
          notiv3 "Blockchain tempo released" ${REGISTRY}/${IMAGE}:${REVISION}
